export default [
  {
    id: 1,
    number: "HEAD23C00115",
    shipper: "COCA COLA",
    consignee: "INVERSIONES MODAPIE S. A.",
    origin: "ARGENTINA",
    destiny: "COSTA RICA",
  },
  {
    id: 2,
    number: "HEAD23C00115",
    shipper: "COCA COLA",
    consignee: "FORD",
    origin: "ARGENTINA",
    destiny: "COSTA RICA",
  },
  {
    id: 3,
    number: "HEAD23C00115",
    shipper: "CALCADOS RAMARIM LTDA",
    consignee: "FORD",
    origin: "BRAZIL",
    destiny: "SPAIN",
  },
  {
    id: 4,
    number: "HEAD23C00115",
    shipper: "CALCADOS RAMARIM LTDA",
    consignee: "INVERSIONES MODAPIE S. A.",
    origin: "BRAZIL",
    destiny: "COSTA RICA",
  },
  {
    id: 5,
    number: "HEAD23C00115",
    shipper: "CALCADOS RAMARIM LTDA",
    consignee: "INVERSIONES MODAPIE S. A.",
    origin: "BRAZIL",
    destiny: "COSTA RICA",
  },
  {
    id: 6,
    number: "HEAD23C00115",
    shipper: "CALCADOS RAMARIM LTDA",
    consignee: "INVERSIONES MODAPIE S. A.",
    origin: "BRAZIL",
    destiny: "COSTA RICA",
  },
  {
    id: 7,
    number: "HEAD23C00115",
    shipper: "CALCADOS RAMARIM LTDA",
    consignee: "INVERSIONES MODAPIE S. A.",
    origin: "BRAZIL",
    destiny: "COSTA RICA",
  },
  {
    id: 8,
    number: "HEAD23C00115",
    shipper: "CALCADOS RAMARIM LTDA",
    consignee: "INVERSIONES MODAPIE S. A.",
    origin: "BRAZIL",
    destiny: "COSTA RICA",
  },
  {
    id: 9,
    number: "HEAD23C00115",
    shipper: "CALCADOS RAMARIM LTDA",
    consignee: "INVERSIONES MODAPIE S. A.",
    origin: "BRAZIL",
    destiny: "COSTA RICA",
  },
  {
    id: 10,
    number: "HEAD23C00115",
    shipper: "CALCADOS RAMARIM LTDA",
    consignee: "INVERSIONES MODAPIE S. A.",
    origin: "BRAZIL",
    destiny: "COSTA RICA",
  },
  {
    id: 11,
    number: "HEAD23C00115",
    shipper: "CALCADOS RAMARIM LTDA",
    consignee: "INVERSIONES MODAPIE S. A.",
    origin: "BRAZIL",
    destiny: "COSTA RICA",
  },
  {
    id: 12,
    number: "HEAD23C00115",
    shipper: "CALCADOS RAMARIM LTDA",
    consignee: "INVERSIONES MODAPIE S. A.",
    origin: "BRAZIL",
    destiny: "COSTA RICA",
  },
];
